name: Teardown QA env on unlabel for PR
on:
  pull_request_target:
    types:
      - unlabeled
jobs:
  delete_qa1_branch:
    if: "!contains(github.event.pull_request.labels.*.name, 'qa-1')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Delete QA-1 branch for this PR
        run: ./.github/scripts/delete_qa_branch_for_pr.sh 1 ${{ github.event.number }}
        shell: bash
  delete_qa2_branch:
    if: "!contains(github.event.pull_request.labels.*.name, 'qa-2')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Delete QA-2 branch for this PR
        run: ./.github/scripts/delete_qa_branch_for_pr.sh 2 ${{ github.event.number }}
        shell: bash
  delete_qa3_branch:
    if: "!contains(github.event.pull_request.labels.*.name, 'qa-3')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Delete QA-3 branch for this PR
        run: ./.github/scripts/delete_qa_branch_for_pr.sh 3 ${{ github.event.number }}
        shell: bash
  delete_qa4_branch:
    if: "!contains(github.event.pull_request.labels.*.name, 'qa-4')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Delete QA-4 branch for this PR
        run: ./.github/scripts/delete_qa_branch_for_pr.sh 4 ${{ github.event.number }}
        shell: bash
